name: Go Benchmark Test

on:
  push:
    branches:
      - main

jobs:
  go-benchmark-checks:
    name: GoBenchmark
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0
          show-progress: false

      - name: Set up Go using version from go.mod
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: 'go.mod'

      - name: Install benchci
        run: curl -sfL https://raw.githubusercontent.com/antrea-io/benchci/main/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Run benchmark
        run: benchci -config test/performance/benchmark.yml
