name: Update Renovate Base Branches
on:
  create:

jobs:
  update-json-and-push:
    if: startsWith(github.ref, 'refs/heads/release-2')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Run updating script
        run: |
          chmod +x update-renovate-baseBranches.sh
          ./update-renovate-baseBranches.sh "${GITHUB_REF#refs/heads/}"
        working-directory: hack/

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes if any
        run: |
          git add .
          git diff --cached --quiet || git commit -m "Update JSON file via workflow"

      - name: Push changes to main branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.ANTREA_WORKFLOW }}
          branch: main
