name: Verify docs

on:
  schedule:
    # every day at 9am
    - cron: '0 9 * * *'

jobs:
  verify:
    name: Verify docs and spelling
    if: github.repository == 'antrea-io/antrea'
    runs-on: [ubuntu-latest]
    steps:
    - name: Check-out code
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
    - name: Set up Go using version from go.mod
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        go-version-file: 'go.mod'
    - name: Run verify scripts
      run: make verify
    - name: Checking for broken Markdown links for main branch
      uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1
      with:
        folder-path: './docs'
        file-path: './README.md, ./CHANGELOG.md, ./CONTRIBUTING.md, ./GOVERNANCE.md, ./MAINTAINERS.md, ./ROADMAP.md, ./SECURITY.md'
        config-file: 'hack/.md_links_config.json'
    - name: Markdownlint
      run: |
        sudo npm install -g markdownlint-cli@0.38.0
        make markdownlint 
